#!/bin/bash
python result/plotAll.py --plot_folder 5task_niiii_bayes_exp_decay0.75
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.75
python result/plotAll.py --plot_folder 5task_niiii_bayes_decay0.9
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.75P
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9a8
python result/plotAll.py --plot_folder 5task_iiiii_bayes_exp_decay0.75P
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9a8
python result/plotAll.py --plot_folder 5task_iiiii_bayes_exp_decay0.9P
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9Pa10
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9a9
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9a9
python result/plotAll.py --plot_folder 5task_niiii_bayes_decay0.75
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9a10
python result/plotAll.py --plot_folder 5task_niiii_bayes_decay0.9P
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9a10
python result/plotAll.py --plot_folder 5task_iiiii_bayes_exp_decay0.75
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9P
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9Pa10
python result/plotAll.py --plot_folder 5task_niiii_bayes_exp_decay0.9P
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9Pa9
python result/plotAll.py --plot_folder 5task_nnnii_bayes_exp_decay0.9P
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9
python result/plotAll.py --plot_folder 5task_nnnii_bayes_exp_decay0.9
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9P
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9Pa8
python result/plotAll.py --plot_folder 5task_niiii_bayes_exp_decay0.75P
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.9
python result/plotAll.py --plot_folder 5task_niiii_bayes_decay0.75P
python result/plotAll.py --plot_folder 5task_niiii_bayes_exp_decay0.9
python result/plotAll.py --plot_folder 5task_iiiii_bayes_exp_decay0.9
python result/plotAll.py --plot_folder 5task_nnnii_bayes_exp_decay0.75P
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9Pa8
python result/plotAll.py --plot_folder 5task_nnnii_bayes_decay0.75
python result/plotAll.py --plot_folder 5task_nnnii_bayes_exp_decay0.75
python result/plotAll.py --plot_folder 5task_iiiii_bayes_decay0.9Pa9

